### PR TITLE
Deprecation warning: Please make sure to add a preprocessor

### PR DESCRIPTION
**Pull request by csimi**
Got this after upgrading to Ember 2.12:

DEPRECATION: Addon files were detected in `..../node_modules/ember-delay/addon`, but no JavaScript preprocessors were found for `ember-delay`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-delay`'s `package.json`.

### CODE REVIEW

**Comment by xtagon** [comment]
I have this deprecation warning in my app too, through `ember-backoff`'s dependency on `ember-delay`. Is something holding this back?

**Comment by GavinJoyce** [comment]
It appears that the [build is failing](https://travis-ci.org/GavinJoyce/ember-delay/builds/227344700). This is also happening on master too though, I'll take a look hopefully over the weekend.

**Comment by GavinJoyce** [comment]
@csimi thanks for the PR. I've fixed the build by [upgrading the addon to ember 2.13](https://github.com/GavinJoyce/ember-delay/pull/11). Doing this also added the `ember-cli-babel` dependency so I'll close this.

https://github.com/GavinJoyce/ember-delay/releases/tag/v0.1.0

**Comment by xtagon** [comment]
Looks like you updated ember-backoff as well. Thanks! 👍

**Pull request closed without merging**
